# Generated by Django 2.1.7 on 2019-06-07 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('review', '0001_initial'),
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='archive.Archive'),
        ),
        migrations.AddField(
            model_name='review',
            name='restaurantId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.Restaurant'),
        ),
    ]
