dist: xenial
language : python

before_script:
        - cd FD_backend
        - python3 manage.py makemigrations users
        - python3 manage.py makemigrations FooDa
        - python3 manage.py migrate

install:
        - pip install django
        - pip install djangorestframework==3.9.3
        - pip install coverage
        - pip install requests
        - pip install django-cors-headers==2.5.3
        - pip install django-tagging
        - pip install django-hitcount
        - pip install django-rest-auth
        - pip install django-allauth  
script :
        - python3 manage.py runserver&
        - sleep 3
        - coverage run --source='.' manage.py test
        - coverage report

          

