dist: xenial
language : python

before_script:
        - python3 FD_backend/manage.py makemigrations users
        - python3 FD_backend/manage.py makemigrations FooDa
        - python3 FD_backend/manage.py migrate

install:
        - pip install django
        - pip install djangorestframework
        - pip install coverage
        - pip install requests
        - pip install hitcount  
        - pip install tagging 
        - pip install allauth  

script :
        - python3 FD_backend/manage.py runserver&
        - sleep 3
        - coverage run --source='.' FD_backend/manage.py test
        - coverage report

          

