# Generated by Django 2.1.7 on 2019-05-21 07:10

from django.conf import settings
from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRanking',
            fields=[
                ('week', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', tagging.fields.TagField(blank=True, max_length=255)),
                ('reviews', models.ManyToManyField(related_name='ranking_reviews', to='Review.Review')),
                ('users', models.ManyToManyField(related_name='ranking_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
