# Generated by Django 2.1.7 on 2019-05-22 06:46

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRanking',
            fields=[
                ('week', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', tagging.fields.TagField(blank=True, max_length=255)),
            ],
        ),
    ]
