# Generated by Django 2.1.7 on 2019-05-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Review', '0001_initial'),
        ('Ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyranking',
            name='reviews',
            field=models.ManyToManyField(related_name='ranking_reviews', to='Review.Review'),
        ),
    ]
