# Generated by Django 2.1.7 on 2019-05-22 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ranking', '0002_weeklyranking_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyranking',
            name='users',
            field=models.ManyToManyField(related_name='ranking_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
