# Generated by Django 2.1.7 on 2019-06-17 15:15

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('eat_when', models.DateTimeField(blank=True)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('public_status', models.BooleanField(default=False)),
                ('score', models.IntegerField(blank=True)),
                ('hits', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('tags', tagging.fields.TagField(blank=True, max_length=255)),
            ],
        ),
    ]
