# Generated by Django 2.1.7 on 2019-05-01 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorCount', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Archive', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuestComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdTime', models.DateTimeField()),
                ('content', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rName', models.CharField(max_length=20)),
                ('rAddress', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('eatWhen', models.DateTimeField()),
                ('postTime', models.DateTimeField(auto_now_add=True)),
                ('publicStatus', models.BooleanField(default=False)),
                ('score', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_archive', to='FooDa.Archive')),
                ('restaurantId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FooDa.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=10, unique=True)),
                ('referedCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TagReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReviewId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ReviewId_review', to='FooDa.Review')),
                ('TagName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Tagname_tag', to='FooDa.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('review1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_review1', to='FooDa.Review')),
                ('review2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_review2', to='FooDa.Review')),
                ('review3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_review3', to='FooDa.Review')),
                ('tag1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_tag1', to='FooDa.Tag')),
                ('tag2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_tag2', to='FooDa.Tag')),
                ('tag3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_tag3', to='FooDa.Tag')),
                ('tag4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_tag4', to='FooDa.Tag')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_user3', to=settings.AUTH_USER_MODEL)),
                ('user3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_user2', to=settings.AUTH_USER_MODEL)),
                ('user4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_user4', to=settings.AUTH_USER_MODEL)),
                ('user5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_user5', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='tag1',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='review_tag1', to='FooDa.Tag'),
        ),
        migrations.AddField(
            model_name='review',
            name='tag2',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='review_tag2', to='FooDa.Tag'),
        ),
        migrations.AddField(
            model_name='review',
            name='tag3',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='review_tag3', to='FooDa.Tag'),
        ),
        migrations.AddField(
            model_name='review',
            name='tag4',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='review_tag4', to='FooDa.Tag'),
        ),
        migrations.AddField(
            model_name='review',
            name='tag5',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='review_tag5', to='FooDa.Tag'),
        ),
    ]
