# Generated by Django 2.1.7 on 2019-05-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rName', models.CharField(max_length=20)),
                ('rAddress', models.TextField()),
            ],
        ),
    ]
